## NumPy 科学计算综合练习


In [ ]:
"""
题目1: 温度数据分析
某城市一周的最高气温为 [28,30,29,31,32,30,29]
- 计算平均气温、最高气温、最低气温
- 找出气温高于30的天数
"""

In [1]:
import numpy as np

In [2]:
arr = np.array([28,30,29,31,32,30,29])

In [3]:
print(np.mean(arr))  # 输出平均气温
print(np.max(arr))   # 输出最高气温
print(np.min(arr))   # 输出最低气温

29.857142857142858
32
28


In [4]:
print(np.sum(arr > 30))  # 输出气温高于30的天数

2


In [ ]:
"""

题目 2:学生成绩统计
某班级 5 名学生的数学成绩为[85,90,78,92, 88]
- 计算成绩的平均分、中位数和标准差
- 将成绩转换为10分制(假设满分为 10)

"""


In [6]:
arr = np.array([85,90,78,92, 88])
print("5student scores:", arr)


5student scores: [85 90 78 92 88]


In [7]:
print("average score:", np.mean(arr))  # 输出平均分
print("median score:",np.median(arr))  # 输出中位数
print("standard deviation:", np.std(arr))  # 输出标准差

average score: 86.6
median score: 88.0
standard deviation: 4.882622246293481


In [9]:
print("10-point scores:", arr/10)  # 将成绩转换为10分制

10-point scores: [8.5 9.  7.8 9.2 8.8]


In [10]:
"""
题目 3:矩阵运算
给定矩阵A=[[1,2],[3,4]]和B=[[5,6],[7,8]]
- 计算A+B和A*B(逐元素乘法)。
- 计算A和B的矩阵乘法(点积)。

"""

'\n题目 3:矩阵运算\n给定矩阵A=[[1,2],[3,4]]和B=[[5,6],[7,8]]\n- 计算A+B和A*B(逐元素乘法)。\n- 计算A和B的矩阵乘法(点积)。\n\n'

In [11]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print("A:", arr1)
print("B:", arr2)

A: [[1 2]
 [3 4]]
B: [[5 6]
 [7 8]]


In [12]:
print("A+B:", arr1 + arr2)  # 逐元素加法
print("A*B (element-wise):", arr1 * arr2)  # 逐元素乘法
print("A dot B:", np.dot(arr1, arr2))  # 矩阵乘法(点积)

A+B: [[ 6  8]
 [10 12]]
A*B (element-wise): [[ 5 12]
 [21 32]]
A dot B: [[19 22]
 [43 50]]


In [13]:
"""
题目 4:随机数据生成
生成一个(3,4)的随机整数数组，范围[0,10)。
- 计算每列的最大值和每行的最小值。
- 将数组中的所有奇数替换为 -1。
"""

'\n题目 4:随机数据生成\n生成一个(3,4)的随机整数数组，范围[0,10)。\n- 计算每列的最大值和每行的最小值。\n- 将数组中的所有奇数替换为 -1。\n'

In [14]:
arr = np.random.randint(0, 10, (3,4))
print("Random array:\n", arr)

Random array:
 [[1 2 1 8]
 [2 5 9 0]
 [5 4 8 4]]


In [16]:
for i in range(0,3):
    print(np.max(arr[i,:]))
for j in range(0,4):
    print(np.min(arr[:,j]))

8
9
8
1
2
1
0


In [17]:
print(np.where(arr % 2 == 1, -1, arr))  # 将数组中的所有奇数替换为 -1

[[-1  2 -1  8]
 [ 2 -1 -1  0]
 [-1  4  8  4]]


In [18]:
"""
题目5:数组变形
创建一个1到12的一维数组,并转换为(3,4)的二维数组。
- 计算每行的和与每列的平均值。
- 将数组展平为一维数组。
"""

'\n题目5:数组变形\n创建一个1到12的一维数组,并转换为(3,4)的二维数组。\n- 计算每行的和与每列的平均值。\n- 将数组展平为一维数组。\n'

In [19]:
arr = np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(np.mean(arr,axis=0))  # 计算每列的平均值
print(np.mean(arr,axis=1))   # 计算每行的平均值

[5. 6. 7. 8.]
[ 2.5  6.5 10.5]


In [24]:
print(np.reshape(arr, -1))  # 将数组展平为一维数组

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
"""
题目5:数组变形
创建一个1到12的一维数组,并转换为(3,4)的二维数组。
- 计算每行的和与每列的平均值。
- 将数组展平为一维数组。
"""

'题目5:数组变形\n创建一个1到12的一维数组,并转换为(3,4)的二维数组。\n- 计算每行的和与每列的平均值。\n- 将数组展平为一维数组。\n'

In [ ]:
"""
题目 6：布尔索引
题目：生成一个 (5, 5) 的随机数组，范围 [0, 20)。  
- 找出数组中大于 10 的元素  
- 将所有大于 10 的元素替换为 0
"""

'\n题目 6：布尔索引\n题目：生成一个 (5, 5) 的随机数组，范围 [0, 20)。  \n-找出数组中大于 10 的元素。  \n- 将所有大于 10 的元素替换为 0。\n'

In [27]:
arr =np.random.randint(0, 20, (5,5))
print("Random array:\n", arr)

Random array:
 [[19  7 16  3  5]
 [ 6 13  2  5 14]
 [18  6  3 19 13]
 [ 6 17 12  9 10]
 [ 4 18  6 11  6]]


In [30]:
print(np.greater(arr, 10))  # 找出数组中大于 10 的元素
print(arr[arr > 10])  # 输出大于 10 的元素
print(np.where(arr > 10, 0, arr))  # 将所有大于 10 的元素替换为 0

[[ True False  True False False]
 [False  True False False  True]
 [ True False False  True  True]
 [False  True  True False False]
 [False  True False  True False]]
[19 16 13 14 18 19 13 17 12 18 11]
[[ 0  7  0  3  5]
 [ 6  0  2  5  0]
 [ 0  6  3  0  0]
 [ 6  0  0  9 10]
 [ 4  0  6  0  6]]


In [31]:
"""
题目 7：统计函数应用
题目：某公司 6 个月的销售额（万元）为 [120, 135, 110, 125, 130, 140]。  
- 计算销售额的总和、均值和方差。  
- 找出销售额最高的月份和最低的月份。
"""

'\n题目 7：统计函数应用\n题目：某公司 6 个月的销售额（万元）为 [120, 135, 110, 125, 130, 140]。  \n- 计算销售额的总和、均值和方差。  \n- 找出销售额最高的月份和最低的月份。\n'

In [32]:
arr = np.array([120, 135, 110, 125, 130, 140])
print("Total sales:", np.sum(arr))  # 输出销售额的总和
print("Average sales:", np.mean(arr))  # 输出销售额的均值
print("Sales variance:", np.var(arr))  # 输出销售额的方差

Total sales: 760
Average sales: 126.66666666666667
Sales variance: 97.22222222222223


In [33]:
print("销售额最高的月份: ", np.argmax(arr) + 1)  # 输出销售额最高的月份
print("销售额最低的月份: ", np.argmin(arr) + 1)  # 输出销售额最低的月份

销售额最高的月份:  6
销售额最低的月份:  3


In [34]:
"""
题目 8：数组拼接
题目：给定 A = [1, 2, 3] 和 B = [4, 5, 6]。  
•水平拼接为 [1, 2, 3, 4, 5, 6]。  
•垂直拼接为 [[1, 2, 3], [4, 5, 6]]。  
"""

'\n题目 8：数组拼接\n题目：给定 A = [1, 2, 3] 和 B = [4, 5, 6]。  \n•水平拼接为 [1, 2, 3, 4, 5, 6]。  \n•垂直拼接为 [[1, 2, 3], [4, 5, 6]]。  \n'

In [35]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [36]:
print("水平拼接:", np.concatenate((arr1, arr2)))  # 水平拼接
print("垂直拼接:\n", np.vstack((arr1, arr2)))  # 垂直拼接

水平拼接: [1 2 3 4 5 6]
垂直拼接:
 [[1 2 3]
 [4 5 6]]
